# Generated by Django 5.2.17 on 2026-09-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(db_default=False, default=False, help_text='Set when the account was given a temporary password. Until they choose their own, every screen sends them to Account settings.'),
        ),
    ]
