# Generated by Django 5.2.17 on 2026-08-24 09:02

import apps.messaging.validators
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sent_as',
            field=models.CharField(blank=True, max_length=32, verbose_name='Sender ID'),
        ),
        migrations.CreateModel(
            name='SchoolMessagingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender_id', models.CharField(help_text='The name parents see the message come from, e.g. "Dapgroup". At most 11 characters, and it must be registered with the gateway before it will carry anything.', max_length=11, validators=[apps.messaging.validators.validate_sender_id], verbose_name='Sender ID')),
                ('provider', models.CharField(choices=[('console', 'Console (development)'), ('bulksmsnigeria', 'BulkSMS Nigeria'), ('termii', 'Termii'), ('africastalking', "Africa's Talking")], default='bulksmsnigeria', help_text='The gateway this Sender ID is registered with.', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Awaiting approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', help_text='Nothing sends under this Sender ID until it is approved.', max_length=20)),
                ('status_note', models.CharField(blank=True, help_text='Why it was rejected or suspended — shown to the school.', max_length=250)),
                ('api_key', models.CharField(blank=True, help_text="Leave blank to send on the platform's master account, which is how the pilot works.", max_length=255, verbose_name='provider API key')),
                ('account_reference', models.CharField(blank=True, help_text='Sub-account or reseller reference on the master account, if the gateway issues one.', max_length=120)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender_ids_approved', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='schools.branch')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='schools.school')),
            ],
            options={
                'verbose_name': 'messaging identity',
                'verbose_name_plural': 'messaging identities',
                'ordering': ['school__name', 'branch__name'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
                'indexes': [models.Index(fields=['school', 'branch'], name='messaging_s_school__f844ad_idx'), models.Index(fields=['status'], name='messaging_s_status_cbd348_idx')],
                'constraints': [models.UniqueConstraint(fields=('school', 'branch'), name='one_messaging_config_per_branch'), models.UniqueConstraint(condition=models.Q(('branch__isnull', True)), fields=('school',), name='one_default_messaging_config_per_school')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
