# Generated by Django 5.2.17 on 2026-09-05 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_message_sent_as_schoolmessagingconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='purpose',
            field=models.CharField(choices=[('transactional', 'Transactional'), ('promotional', 'Promotional')], default='transactional', help_text="Transactional messages use the gateway's DND route and reach parents who have Do-Not-Disturb on. Promotional messages do not, and are blocked overnight.", max_length=20),
        ),
        migrations.AlterField(
            model_name='schoolmessagingconfig',
            name='provider',
            field=models.CharField(choices=[('console', 'Console (development)'), ('bulksmsnigeria', 'BulkSMS Nigeria'), ('termii', 'Termii'), ('africastalking', "Africa's Talking")], default='termii', help_text='The gateway this Sender ID is registered with.', max_length=32),
        ),
    ]
