# Generated by Django 5.2.17 on 2026-09-13 23:01

import apps.messaging.validators
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_move_configs_to_termii'),
        ('schools', '0002_school_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolmessagingconfig',
            name='whatsapp_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolmessagingconfig',
            name='whatsapp_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_identities_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolmessagingconfig',
            name='whatsapp_device_id',
            field=models.CharField(blank=True, help_text="The gateway's id for the school's connected WhatsApp Business number.", max_length=120, verbose_name='WhatsApp device ID'),
        ),
        migrations.AddField(
            model_name='schoolmessagingconfig',
            name='whatsapp_provider',
            field=models.CharField(blank=True, choices=[('console', 'Console (development)'), ('bulksmsnigeria', 'BulkSMS Nigeria'), ('termii', 'Termii'), ('africastalking', "Africa's Talking"), ('termii_whatsapp', 'Termii WhatsApp')], help_text='Blank means this school has not set up WhatsApp.', max_length=32, verbose_name='WhatsApp gateway'),
        ),
        migrations.AddField(
            model_name='schoolmessagingconfig',
            name='whatsapp_status',
            field=models.CharField(choices=[('pending', 'Awaiting approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', help_text="Nothing sends over WhatsApp until Meta has approved the school's WhatsApp Business account.", max_length=20, verbose_name='WhatsApp status'),
        ),
        migrations.AddField(
            model_name='schoolmessagingconfig',
            name='whatsapp_status_note',
            field=models.CharField(blank=True, help_text='Why WhatsApp was rejected or suspended — shown to the school.', max_length=250, verbose_name='WhatsApp note'),
        ),
        migrations.AlterField(
            model_name='schoolmessagingconfig',
            name='provider',
            field=models.CharField(choices=[('console', 'Console (development)'), ('bulksmsnigeria', 'BulkSMS Nigeria'), ('termii', 'Termii'), ('africastalking', "Africa's Talking"), ('termii_whatsapp', 'Termii WhatsApp')], default='termii', help_text='The gateway this Sender ID is registered with.', max_length=32),
        ),
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='What staff choose on the compose screen, e.g. "Fee reminder".', max_length=80)),
                ('provider', models.CharField(choices=[('console', 'Console (development)'), ('bulksmsnigeria', 'BulkSMS Nigeria'), ('termii', 'Termii'), ('africastalking', "Africa's Talking"), ('termii_whatsapp', 'Termii WhatsApp')], default='termii_whatsapp', help_text='The gateway this template is registered with.', max_length=32)),
                ('template_id', models.CharField(help_text="The gateway's id for the template, from its dashboard.", max_length=120, verbose_name='template ID')),
                ('category', models.CharField(choices=[('utility', 'Utility'), ('marketing', 'Marketing')], default='utility', max_length=20)),
                ('language', models.CharField(default='en', max_length=10)),
                ('body', models.TextField(help_text='The approved text exactly as registered, with variables written <%parent_name%>. Available: <%parent_name%>, <%student_name%>, <%school_name%>, <%message%>.', validators=[apps.messaging.validators.validate_template_body])),
                ('status', models.CharField(choices=[('pending', 'Awaiting approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', help_text='Nothing sends with this template until Meta has approved it.', max_length=20)),
                ('status_note', models.CharField(blank=True, help_text='Why it was rejected or paused.', max_length=250)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='schools.branch')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='schools.school')),
            ],
            options={
                'verbose_name': 'WhatsApp template',
                'ordering': ['school__name', 'name'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='messaging.whatsapptemplate'),
        ),
        migrations.AddIndex(
            model_name='whatsapptemplate',
            index=models.Index(fields=['school', 'branch'], name='messaging_w_school__856cc3_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsapptemplate',
            index=models.Index(fields=['status'], name='messaging_w_status_b79807_idx'),
        ),
        migrations.AddConstraint(
            model_name='whatsapptemplate',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='one_whatsapp_template_name_per_school'),
        ),
    ]
