# Generated by Django 5.2.17 on 2026-08-13 22:53

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Without the arm, e.g. "JSS 1" or "Primary 3".', max_length=60)),
                ('level', models.PositiveSmallIntegerField(choices=[(10, 'Nursery'), (20, 'Primary'), (30, 'Junior Secondary'), (40, 'Senior Secondary')])),
                ('year_in_level', models.PositiveSmallIntegerField(default=1, help_text='Position inside the level, used for ordering. Pre-KG is 0, KG 1 is 1, Primary 1 is 1, and so on.', verbose_name='year within level')),
                ('stream', models.CharField(blank=True, help_text='Optional, e.g. "Science", "Arts", "A". Leave blank if the year is a single group.', max_length=40, verbose_name='stream / arm')),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='schools.branch')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='schools.school')),
            ],
            options={
                'verbose_name': 'class',
                'verbose_name_plural': 'classes',
                'ordering': ['level', 'year_in_level', 'stream', 'name'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(blank=True, help_text='Optional short code, e.g. "MTH".', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='schools.branch')),
                ('classes', models.ManyToManyField(blank=True, help_text='The classes this subject is taught in.', related_name='subjects', to='academics.class')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='schools.school')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['school', 'branch'], name='academics_c_school__a670b6_idx'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['branch', 'level', 'year_in_level'], name='academics_c_branch__6d91c6_idx'),
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.UniqueConstraint(fields=('branch', 'name', 'stream'), name='unique_class_per_branch'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['school', 'branch'], name='academics_s_school__a09686_idx'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('branch', 'name'), name='unique_subject_per_branch'),
        ),
    ]
