# Generated by Django 5.2.17 on 2026-08-14 23:34

import apps.students.validators
import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.manager
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission_number', models.CharField(help_text='The school\'s own number, e.g. "FA/2025/001". Unique within this branch.', max_length=32)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80, verbose_name='surname')),
                ('other_names', models.CharField(blank=True, max_length=120)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('date_admitted', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('graduated', 'Graduated'), ('withdrawn', 'Withdrawn')], default='active', max_length=20)),
                ('parent_name', models.CharField(max_length=160, verbose_name='parent / guardian name')),
                ('parent_phone', models.CharField(help_text='Mobile number, e.g. 0803 123 4567.', max_length=20, validators=[apps.students.validators.validate_phone], verbose_name='parent / guardian phone')),
                ('parent_email', models.EmailField(blank=True, max_length=254, verbose_name='parent / guardian email')),
                ('address', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='schools.branch')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='schools.school')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.class', verbose_name='class')),
            ],
            options={
                'ordering': ['school_class__level', 'school_class__year_in_level', 'school_class__stream', 'last_name', 'first_name'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
                'indexes': [models.Index(fields=['school', 'branch'], name='students_st_school__20e960_idx'), models.Index(fields=['branch', 'status'], name='students_st_branch__4eab65_idx'), models.Index(fields=['school_class', 'status'], name='students_st_school__0da202_idx'), models.Index(fields=['last_name', 'first_name'], name='students_st_last_na_3e473b_idx')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Upper('admission_number'), models.F('branch'), name='unique_admission_number_per_branch', violation_error_message='Another student at this branch already has that admission number.')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
