# Generated by Django 5.2.17 on 2026-08-24 00:23

import apps.payments.models
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fees', '0002_term_due_date'),
        ('schools', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date_paid', models.DateField(default=django.utils.timezone.localdate, help_text='When the money was received, not when it was typed in.')),
                ('label', models.CharField(choices=[('school_fees', 'School Fees'), ('uniform', 'Uniform'), ('books', 'Books'), ('development', 'Development'), ('other', 'Other')], default='school_fees', help_text='What the payment was for. Descriptive only — the balance is one combined figure.', max_length=20)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Bank transfer'), ('pos', 'POS'), ('other', 'Other')], default='transfer', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Teller number, transfer reference, POS stub — whatever the receipt shows.', max_length=120)),
                ('source', models.CharField(choices=[('manual', 'Recorded by staff'), ('gateway', 'Online payment'), ('bank_import', 'Bank import')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('void', 'Voided')], default='confirmed', max_length=20)),
                ('receipt', models.FileField(blank=True, help_text="The parent's bank slip or POS receipt. Image or PDF.", null=True, upload_to=apps.payments.models.receipt_upload_to, verbose_name='receipt attachment')),
                ('note', models.CharField(blank=True, max_length=250)),
                ('gateway_provider', models.CharField(blank=True, max_length=40)),
                ('gateway_reference', models.CharField(blank=True, max_length=160)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=250)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='schools.branch')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_confirmed', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_recorded', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='students.student')),
                ('term', models.ForeignKey(help_text='The term this payment is credited to.', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='fees.term')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_voided', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_paid', '-id'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
                'indexes': [models.Index(fields=['school', 'branch'], name='payments_pa_school__3e64a0_idx'), models.Index(fields=['student', 'term'], name='payments_pa_student_3b032f_idx'), models.Index(fields=['term', 'status'], name='payments_pa_term_id_c4c325_idx'), models.Index(fields=['branch', 'status', '-date_paid'], name='payments_pa_branch__aee034_idx')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
