# Generated by Django 5.2.17 on 2026-08-24 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='due_date',
            field=models.DateField(blank=True, help_text='Optional. Unpaid balances are only marked overdue after this date.', null=True, verbose_name='fees due by'),
        ),
    ]
