# Generated by Django 5.2.17 on 2026-09-05 10:05

import apps.admissions.models
import apps.admissions.validators
import apps.students.validators
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('schools', '0002_school_logo'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionFeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.CharField(help_text='e.g. "2025/2026".', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=250)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_fee_schedules', to='schools.branch')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='schools.school')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_fee_schedules', to='academics.class', verbose_name='class')),
            ],
            options={
                'verbose_name': 'admission fee schedule',
                'ordering': ['-academic_year', 'school_class__level', 'school_class__year_in_level', 'school_class__stream'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionFeeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('kind', models.CharField(choices=[('admission', 'Admission fee'), ('intake', 'Intake item'), ('books', 'Compulsory books')], default='intake', max_length=20)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_fee_items', to='schools.branch')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='schools.school')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='admissions.admissionfeeschedule')),
            ],
            options={
                'ordering': ['kind', 'position', 'id'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enquiry_validity_days', models.PositiveSmallIntegerField(default=21, help_text='An enquiry that has not become an application within this many days expires. It is kept, not deleted.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='enquiry valid for (days)')),
                ('reminder_after_days', models.PositiveSmallIntegerField(default=7, help_text='How long to wait before emailing the parent to continue their application. Must be inside the validity window.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='send the reminder after (days)')),
                ('bursar_can_view_applicants', models.BooleanField(default=False, help_text='Off by default: a bursar sees admission-fee payments without seeing the applicant pipeline. Turn on for a school whose bursar runs the front desk. A bursar never decides on an application either way.', verbose_name='bursar can see applicants')),
                ('require_payment_before_enrolment', models.BooleanField(default=True, help_text='Refuse to enrol an accepted applicant until the admission fee has been confirmed. Turn off for a school that admits first and collects afterwards.')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='schools.branch')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='schools.school')),
            ],
            options={
                'verbose_name': 'admissions settings',
                'verbose_name_plural': 'admissions settings',
                'ordering': ['school__name'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(blank=True, help_text='Generated. What staff and parents quote on the phone.', max_length=24)),
                ('status', models.CharField(choices=[('enquiry', 'Enquiry'), ('application', 'Application'), ('assessed', 'Assessed'), ('offered', 'Offer made'), ('rejected', 'Rejected'), ('enrolled', 'Enrolled'), ('expired', 'Expired'), ('withdrawn', 'Withdrawn')], db_index=True, default='enquiry', max_length=20)),
                ('source', models.CharField(choices=[('online', 'Online enquiry form'), ('walk_in', 'Walk-in / front desk'), ('phone', 'Phone call'), ('imported', 'Imported')], default='online', max_length=20)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80, verbose_name='surname')),
                ('other_names', models.CharField(blank=True, max_length=120)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('level', models.PositiveSmallIntegerField(choices=[(10, 'Nursery'), (20, 'Primary'), (30, 'Junior Secondary'), (40, 'Senior Secondary')], help_text='The band applied for. Decides which requirements apply.')),
                ('parent_name', models.CharField(max_length=160, verbose_name='parent / guardian name')),
                ('parent_phone', models.CharField(help_text='Mobile number, e.g. 0803 123 4567.', max_length=20, validators=[apps.students.validators.validate_phone], verbose_name='parent / guardian phone')),
                ('parent_email', models.EmailField(blank=True, help_text='Where the reminder and the decision are sent. Without one, neither can go out.', max_length=254, verbose_name='parent / guardian email')),
                ('previous_school', models.CharField(blank=True, max_length=200)),
                ('heard_about', models.CharField(blank=True, choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('whatsapp', 'WhatsApp'), ('website', 'School website'), ('referral', 'A friend or family member'), ('flyer', 'Flyer or banner'), ('radio', 'Radio or TV'), ('place_of_worship', 'Church or mosque'), ('passing_by', 'Passed by the school'), ('other', 'Somewhere else')], max_length=32, verbose_name='how they heard about the school')),
                ('expires_at', models.DateTimeField(blank=True, help_text="Set from the school's admissions settings when the enquiry is first saved.", null=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('nationality', models.CharField(blank=True, max_length=80)),
                ('state_of_origin', models.CharField(blank=True, max_length=80)),
                ('parent_occupation', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True, help_text='Anything the school should know -- allergies, a sibling already here, learning support.')),
                ('passport_photo', models.FileField(blank=True, null=True, upload_to=apps.admissions.models.document_upload_to, validators=[apps.admissions.validators.validate_photo])),
                ('birth_certificate', models.FileField(blank=True, null=True, upload_to=apps.admissions.models.document_upload_to, validators=[apps.admissions.validators.validate_document])),
                ('previous_results', models.FileField(blank=True, null=True, upload_to=apps.admissions.models.document_upload_to, validators=[apps.admissions.validators.validate_document], verbose_name='previous school results')),
                ('transfer_letter', models.FileField(blank=True, null=True, upload_to=apps.admissions.models.document_upload_to, validators=[apps.admissions.validators.validate_document], verbose_name='transfer letter / testimonial')),
                ('immunisation_record', models.FileField(blank=True, null=True, upload_to=apps.admissions.models.document_upload_to, validators=[apps.admissions.validators.validate_document])),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True, help_text="The reason, in the school's own words.")),
                ('decision_sent_at', models.DateTimeField(blank=True, help_text='When the parent was emailed the outcome.', null=True)),
                ('enrolled_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('closing_note', models.CharField(blank=True, max_length=250)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='schools.branch')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_decisions', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='schools.school')),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicants', to='academics.class', verbose_name='class applied for')),
                ('student', models.OneToOneField(blank=True, help_text='Who this applicant became. Set once, at enrolment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicant', to='students.student')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Bank transfer'), ('pos', 'POS'), ('other', 'Other')], default='transfer', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('void', 'Voided')], default='confirmed', max_length=20)),
                ('received_on', models.DateField(default=django.utils.timezone.localdate)),
                ('reference', models.CharField(blank=True, help_text='Teller number, transfer reference.', max_length=120)),
                ('note', models.CharField(blank=True, max_length=250)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_payments', to='schools.branch')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_payments_recorded', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='schools.school')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='admissions.applicant')),
            ],
            options={
                'ordering': ['-received_on', '-id'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_for', models.DateField(blank=True, help_text='When the applicant is due to sit it.', null=True)),
                ('sat_on', models.DateField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('max_score', models.DecimalField(decimal_places=2, default=Decimal('100'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('1'))])),
                ('outcome', models.CharField(choices=[('pending', 'Not yet sat'), ('passed', 'Passed'), ('failed', 'Did not pass'), ('absent', 'Did not attend')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='admissions.applicant')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_assessments', to='schools.branch')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_assessments_recorded', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='schools.school')),
            ],
            options={
                'ordering': ['-scheduled_for', '-id'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RequirementSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.PositiveSmallIntegerField(choices=[(10, 'Nursery'), (20, 'Primary'), (30, 'Junior Secondary'), (40, 'Senior Secondary')])),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, help_text='Optional. Shown to staff on the settings screen.', max_length=250)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='schools.branch')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='schools.school')),
            ],
            options={
                'verbose_name': 'admission requirement set',
                'ordering': ['school__name', 'level'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('passport_photo', 'Passport photograph'), ('birth_certificate', 'Birth certificate'), ('previous_results', 'Previous school results'), ('transfer_letter', 'Transfer letter / testimonial'), ('immunisation_record', 'Immunisation record'), ('entrance_exam', 'Entrance examination')], max_length=32)),
                ('is_required', models.BooleanField(default=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_set', to='schools.branch')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='schools.school')),
                ('requirement_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='admissions.requirementset')),
            ],
            options={
                'ordering': ['position', 'id'],
                'abstract': False,
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='admissionfeeschedule',
            index=models.Index(fields=['school', 'branch'], name='admissions__school__e4c24c_idx'),
        ),
        migrations.AddIndex(
            model_name='admissionfeeschedule',
            index=models.Index(fields=['branch', 'academic_year'], name='admissions__branch__0fb0ec_idx'),
        ),
        migrations.AddConstraint(
            model_name='admissionfeeschedule',
            constraint=models.UniqueConstraint(fields=('school_class', 'academic_year'), name='one_admission_schedule_per_class_year'),
        ),
        migrations.AddIndex(
            model_name='admissionfeeitem',
            index=models.Index(fields=['school', 'branch'], name='admissions__school__91227d_idx'),
        ),
        migrations.AddIndex(
            model_name='admissionfeeitem',
            index=models.Index(fields=['schedule', 'position'], name='admissions__schedul_906027_idx'),
        ),
        migrations.AddConstraint(
            model_name='admissionfeeitem',
            constraint=models.UniqueConstraint(fields=('schedule', 'name'), name='unique_admission_item_name_per_schedule'),
        ),
        migrations.AddIndex(
            model_name='admissionsconfig',
            index=models.Index(fields=['school', 'branch'], name='admissions__school__98ec78_idx'),
        ),
        migrations.AddConstraint(
            model_name='admissionsconfig',
            constraint=models.UniqueConstraint(fields=('school',), name='one_admissions_config_per_school'),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['school', 'branch'], name='admissions__school__358024_idx'),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['branch', 'status'], name='admissions__branch__6207e9_idx'),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['status', 'expires_at'], name='admissions__status_48364d_idx'),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['last_name', 'first_name'], name='admissions__last_na_248e2c_idx'),
        ),
        migrations.AddConstraint(
            model_name='applicant',
            constraint=models.UniqueConstraint(fields=('school', 'reference'), name='unique_applicant_reference_per_school', violation_error_message='Another applicant at this school already has that reference.'),
        ),
        migrations.AddIndex(
            model_name='admissionpayment',
            index=models.Index(fields=['school', 'branch'], name='admissions__school__564fe6_idx'),
        ),
        migrations.AddIndex(
            model_name='admissionpayment',
            index=models.Index(fields=['applicant', 'status'], name='admissions__applica_c0b696_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['school', 'branch'], name='admissions__school__0119a2_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['branch', 'outcome'], name='admissions__branch__c05c93_idx'),
        ),
        migrations.AddIndex(
            model_name='requirementset',
            index=models.Index(fields=['school', 'branch'], name='admissions__school__4c31b6_idx'),
        ),
        migrations.AddConstraint(
            model_name='requirementset',
            constraint=models.UniqueConstraint(fields=('school', 'branch', 'level'), name='one_requirement_set_per_branch_level'),
        ),
        migrations.AddConstraint(
            model_name='requirementset',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', True)), fields=('school', 'level'), name='one_requirement_set_per_school_level'),
        ),
        migrations.AddIndex(
            model_name='requirement',
            index=models.Index(fields=['school', 'branch'], name='admissions__school__4aeb27_idx'),
        ),
        migrations.AddConstraint(
            model_name='requirement',
            constraint=models.UniqueConstraint(fields=('requirement_set', 'kind'), name='unique_requirement_kind_per_set'),
        ),
    ]
