# Generated by Django 5.2.17 on 2026-08-12 23:46

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('plan', models.CharField(choices=[('trial', 'Trial'), ('starter', 'Starter'), ('growth', 'Growth'), ('enterprise', 'Enterprise')], default='trial', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('trialing', 'Trialing'), ('past_due', 'Past due'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='trialing', max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'ordering': ['name'],
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=120)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('head', models.ForeignKey(blank=True, help_text='Principal or branch administrator responsible for this campus.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches_headed', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='schools.school')),
            ],
            options={
                'verbose_name_plural': 'branches',
                'ordering': ['school__name', 'name'],
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
                'constraints': [models.UniqueConstraint(fields=('school', 'name'), name='unique_branch_name_per_school')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
