# Generated by Django 5.2.17 on 2026-08-26 13:02

import apps.schools.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.FileField(blank=True, help_text="Optional. Appears on your screens and on payment receipts. Without one, your school's initial is shown instead.", null=True, upload_to=apps.schools.models.logo_upload_to, validators=[apps.schools.models.validate_logo]),
        ),
    ]
