# Generated by Django 5.2.17 on 2026-09-26 11:01

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_school_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=40)),
                ('enabled', models.BooleanField()),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module_changes', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_states', to='schools.school')),
            ],
            options={
                'verbose_name': 'school module',
                'ordering': ['school__name', 'key'],
                'base_manager_name': 'all_objects',
                'default_manager_name': 'objects',
                'indexes': [models.Index(fields=['school', 'key'], name='schools_sch_school__eeb89c_idx')],
                'constraints': [models.UniqueConstraint(fields=('school', 'key'), name='unique_module_per_school')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
